# Generated by Django 4.0.3 on 2024-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CO2',
        ),
    ]
