# Generated by Django 4.0.3 on 2024-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesslog_delete_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='service_name',
            field=models.CharField(choices=[('Home', 'Home'), ('Dashboard', 'Dashboard'), ('Profile', 'Profile'), ('Settings', 'Settings'), ('Reports', 'Reports'), ('Teste', 'Teste')], max_length=100),
        ),
    ]
